name: Build and Push Flatpak

on:
  push:
    branches:
      - 'sleepy'
    paths:
      - 'moe.launcher.sleepy-launcher.yml'
      
  workflow_dispatch:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-22.04
    container:
      image: fedora:40
      options: --privileged
    steps:
    - name: Install Deps and Setup environment
      run: |
        dnf install -y wget flatpak gtk4-devel gtk4 libadwaita git curl openssl-devel rust cargo xorg-x11-server-Xvfb flatpak-builder python3-aiohttp python3-tenacity python3-gobject
        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        wget https://raw.githubusercontent.com/flatpak/flat-manager/f6ef84fc39659065c7323e7680adff20add9068a/flat-manager-client -O /usr/bin/flat-manager-client
        chmod +x /usr/bin/flat-manager-client
        git config --global protocol.file.allow always
    - uses: actions/checkout@v4
      with:
        ref: sleepy
        submodules: true
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.5
      name: "Build"
      with:
        bundle: moe.launcher.sleepy-launcher.flatpak
        build-bundle: false
        manifest-path: moe.launcher.sleepy-launcher.yml
        cache-key: flatpak-builder-${{ github.sha }}
    - uses: flatpak/flatpak-github-actions/flat-manager@v6.5
      name: "Deploy"
      with:
        repository: stable
        flat-manager-url: ${{ secrets.REPO_URL }}
        token: ${{ secrets.REPO_TOKEN }}
